FROM ubuntu:18.04 as builder

ARG KUBERNETES_VERSION=v1.15.7

RUN apt-get update && apt-get install -y curl
RUN curl -L https://dl.k8s.io/${KUBERNETES_VERSION}/kubernetes-client-linux-amd64.tar.gz -o /kubectl.tar.gz \
    && tar -zxvf /kubectl.tar.gz

FROM scratch

COPY --from=builder /kubernetes/client/bin/kubectl /kubectl
ENTRYPOINT ["/kubectl"]
