FROM jenkins/inbound-agent:4.10-3

USER root

ARG VAULT_VERSION=1.5.3
ARG PACKER_VERSION=1.8.1
ARG TERRAFORM_1_VERSION=1.0.5
ARG TERRAFORM_1_1_VERSION=1.1.6
ARG KUBECTL_VERSION=1.22.9
ARG HELM_VERSION=3.8.1
ARG ANSIBLE_VERSION=2.10.3
ARG TERRAFORM_DOCS_VERSION=0.10.1
ARG CONFTEST_VERSION=0.23.0
ARG TRIVY_VERSION=0.27.1
ARG SONAR_SCANNER_VERSION=4.7.0.2747
ARG INFRACOST_VERSION=v0.9.24
ARG SONOBUOY_VERSION=0.56.6

RUN apt-get update && apt-get dist-upgrade -y \
      && apt-get install -y \
        git \
        apt-transport-https \
        curl \
        wget \
        init \
        openssh-server openssh-client \
        software-properties-common \
        unzip \
        libffi-dev \
        jq \
        python3-pip \
      && rm -rf /var/lib/apt/lists/* \

    #### install aws cli
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
      && unzip awscliv2.zip && ./aws/install && rm awscliv2.zip && rm -rf aws \

    #### install boto3
    && pip3 install --no-cache-dir -U boto3 checkov pre-commit \

    #### install ansible
    && pip3 install --no-cache-dir ansible==${ANSIBLE_VERSION} \

    #### install vault
    && curl "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_arm64.zip" -o "vault.zip" \
      && unzip vault.zip && mv vault /usr/bin && rm vault.zip \

    #### install packer
    && curl "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_arm64.zip" -o "packer.zip" \
      && unzip packer.zip && mv packer /usr/bin && rm packer.zip \

    #### install kubectl
    && curl "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/arm64/kubectl" -o "kubectl" \
      && chmod +x kubectl && mv kubectl /usr/bin \

    #### install helm
    && curl -L "https://get.helm.sh/helm-v${HELM_VERSION}-linux-arm64.tar.gz" -o "helm.tar.gz" \
      && tar -xvzf helm.tar.gz && chmod +x linux-arm64/helm && mv linux-arm64/helm /usr/bin \
      && rm -rf linux-arm64 helm.tar.gz \

    #### install terraform-docs
    && curl -L "https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-arm64" -o "terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-arm64" \
      && mv terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-arm64 /usr/local/bin/terraform-docs \
      && chmod a+x /usr/local/bin/terraform-docs \

    #### install conftest (aka opa)
    && curl -L "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" -o "conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" \
      && tar xzf "conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" \
      && mv conftest /usr/local/bin \
      && chmod +x /usr/local/bin/conftest \
      && rm "conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" \

    #### install trivy
    && wget "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-ARM64.deb" \
      && dpkg -i "trivy_${TRIVY_VERSION}_Linux-ARM64.deb" \
      && rm "trivy_${TRIVY_VERSION}_Linux-ARM64.deb" \
      && pip3 install --no-cache-dir pyyaml nested-lookup \
 
    #### install sonar scanner cli
    && wget "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip" \
      && wget "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip.sha256" \
      && echo $(cat "sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip.sha256")  "sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip" | sha256sum -c \
      && unzip "sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip" \
      && rm "sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip" "sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip.sha256" \
      && chmod +x "sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner" \
      && mv "sonar-scanner-${SONAR_SCANNER_VERSION}" "/opt/sonar-scanner-${SONAR_SCANNER_VERSION}" \
      && ln -s "/opt/sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner" /usr/local/bin/sonar-scanner \

    #### install infracost
    && wget "https://github.com/infracost/infracost/releases/download/${INFRACOST_VERSION}/infracost-linux-arm64.tar.gz" \
      && wget "https://github.com/infracost/infracost/releases/download/${INFRACOST_VERSION}/infracost-linux-arm64.tar.gz.sha256" \
      && sha256sum -c "infracost-linux-arm64.tar.gz.sha256" \
      && mkdir /opt/infracost_bin \
      && tar xf infracost-linux-arm64.tar.gz -C /opt/infracost_bin/ \
      && rm infracost-linux-arm64.tar.gz infracost-linux-arm64.tar.gz.sha256 \
      && chmod +x /opt/infracost_bin/infracost-linux-arm64 \
      && mv /opt/infracost_bin/infracost-linux-arm64 /opt/infracost_bin/infracost \
      && ln -s /opt/infracost_bin/infracost /usr/local/bin/infracost \

    #### install sonobuoy
    && wget "https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/sonobuoy_${SONOBUOY_VERSION}_linux_arm64.tar.gz" \
      && wget "https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/sonobuoy_${SONOBUOY_VERSION}_checksums.txt" \
      && sha256sum --ignore-missing -c "sonobuoy_${SONOBUOY_VERSION}_checksums.txt" \
      && tar -xvzf "sonobuoy_${SONOBUOY_VERSION}_linux_arm64.tar.gz" \
      && mv ./sonobuoy /usr/local/bin/sonobuoy \
      && chmod +x /usr/local/bin/sonobuoy \
      && rm "sonobuoy_${SONOBUOY_VERSION}_linux_arm64.tar.gz" "sonobuoy_${SONOBUOY_VERSION}_checksums.txt" LICENSE

RUN mkdir -p /etc/tfenv \
  && git clone --depth 1 https://github.com/tfutils/tfenv.git /etc/tfenv \
  && chown -R jenkins /etc/tfenv

USER jenkins
    #### install terraform with tfenv and helm diff

RUN helm plugin install https://github.com/databus23/helm-diff

ENV PATH "$PATH:/etc/tfenv/bin"
RUN tfenv install ${TERRAFORM_1_VERSION} \
      && tfenv install ${TERRAFORM_1_1_VERSION} \
      && tfenv use ${TERRAFORM_1_VERSION}

