name: Upgrade Pip

on:
  workflow_dispatch:

jobs:
  upgrade-pip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip
